index:
    path: /
    controller: App\Controller\DefaultController::index

laurentiu_tibea:
  path: "/laurentiu_tibea"
  controller: App\Controller\laurentiuTibeaController::index

vicky_rusu:
  path: /vicky_rusu
  controller: App\Controller\VickyRusuController::index

balau_razvan:
  path: "/balau_razvan"
  controller: App\Controller\balauRazvanController::index
  
