#index:
#    path: /
#    controller: App\Controller\DefaultController::index

laurentiu_tibea:
  path: "/laurentiu_tibea"
  controller: App\Controller\laurentiuTibeaController::index

  jude_bogdan:
  path: "/jude_bogdan"
  controller: App\Controller\judeBogdanController::index